import assert from 'node:assert/strict';
import test from 'node:test';

import { avaliarLock, validarLockDoRepositorio } from './validar-lock-python.mjs';

const LOCK_OK = `# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.txt --generate-hashes --universal --python-version 3.12 --output-file requirements.lock.txt
fastapi==0.141.1 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via -r requirements.txt
uvicorn==0.52.4 \\
    --hash=sha256:cccc
    # via -r requirements.txt
`;

const DIRETAS = 'fastapi==0.141.1\nuvicorn[standard]==0.52.4\n';

test('aceita lock com versoes exatas, hashes e cabecalho de origem', () => {
  const resultado = avaliarLock(LOCK_OK, DIRETAS);
  assert.equal(resultado.aprovado, true);
  assert.equal(resultado.pacotes, 2);
});

test('reprova requisito sem hash', () => {
  const semHash = LOCK_OK.replace('    --hash=sha256:cccc\n', '');
  assert.equal(avaliarLock(semHash, DIRETAS).aprovado, false);
  assert.match(avaliarLock(semHash, DIRETAS).mensagem, /sem hash/);
});

test('reprova requisito sem versao exata', () => {
  const frouxo = LOCK_OK.replace('uvicorn==0.52.4', 'uvicorn>=0.52.4');
  assert.match(avaliarLock(frouxo, DIRETAS).mensagem, /versao exata/);
});

test('reprova quando uma dependencia direta nao aparece no lock', () => {
  const semUvicorn = LOCK_OK.split('uvicorn==')[0];
  assert.match(avaliarLock(semUvicorn, DIRETAS).mensagem, /uvicorn/);
});

test('reprova quando a versao direta diverge da versao travada', () => {
  const divergente = LOCK_OK.replace('uvicorn==0.52.4', 'uvicorn==0.52.3');
  assert.match(avaliarLock(divergente, DIRETAS).mensagem, /diverge/);
});

test('reprova lock sem cabecalho que registre como foi gerado', () => {
  const semCabecalho = LOCK_OK.split('\n').slice(2).join('\n');
  assert.match(avaliarLock(semCabecalho, DIRETAS).mensagem, /cabecalho/);
});

test('o lock real do repositorio e reproduzivel e completo', () => {
  assert.match(validarLockDoRepositorio(), /Lock Python valido/);
});
